;;* BOT Entity Macros
(in-package :hactar)

;;** defskill

(defmacro defskill (name description &body body)
  "Define a skill that provides instructions to the LLM.

   Usage:
   (defskill :react-router-patterns
     \"React Router patterns\"
     :instructions \"When working with React Router...\"
     :rules \"Always use TypeScript\"
     :examples ((:title \"Example\" :code \"...\")))"
  (let ((instructions (getf body :instructions))
        (rules (getf body :rules))
        (examples (getf body :examples)))
    `(register-skill ,name
                     :description ,description
                     :instructions ,instructions
                     :rules ,rules
                     :examples ',examples)))

;;** defbehavior

(defmacro defbehavior (name description &body body)
  "Define a composable behavior that can attach to entities via tags.

   Usage:
   (defbehavior authenticated
     \"Adds authentication requirements\"
     :tags (:authenticated :protected)
     :skill :auth-patterns
     :rule (lambda (entity) ...)
     :validator (lambda (entity) ...)
     :before-create (lambda (entity) ...))"
  (let ((tags (getf body :tags))
        (skill (getf body :skill))
        (rule (getf body :rule))
        (generator (getf body :generator))
        (validator (getf body :validator))
        (before-create (getf body :before-create))
        (after-create (getf body :after-create))
        (before-update (getf body :before-update))
        (after-update (getf body :after-update))
        (before-delete (getf body :before-delete))
        (after-delete (getf body :after-delete)))
    `(register-behavior ',name
                        :description ,description
                        :tags ',tags
                        :skill ,skill
                        :rule ,rule
                        :generator ,generator
                        :validator ,validator
                        :before-create ,before-create
                        :after-create ,after-create
                        :before-update ,before-update
                        :after-update ,after-update
                        :before-delete ,before-delete
                        :after-delete ,after-delete)))

;;** deftag

(defmacro deftag (name description &body body)
  "Define a tag that groups behaviors.

   Usage:
   (deftag :api
     \"Tag for API endpoints\"
     :behaviors (json-response error-handling)
     :inherits (:restful)
     :skills (:api-patterns))"
  (let ((behaviors (getf body :behaviors))
        (inherits (getf body :inherits))
        (requires (getf body :requires))
        (skills (getf body :skills)))
    `(register-tag ,name
                   :description ,description
                   :behaviors ',behaviors
                   :inherits ',inherits
                   :requires ',requires
                   :skills ',skills)))

;;** defentity

(defmacro defentity (name description &body body)
  "Define a base entity type and auto-generate the def<entity> macro.

   This creates:
   1. The entity type definition in *entity-registry*
   2. A def<name> macro for framework-specific implementations
   3. CRUD commands: /<name>.create, /<name>.list, etc.
   4. CLI subcommands: <name>.create, <name>.list, etc.

   Usage:
   (defentity frameworkroute
     \"A route represents an HTTP endpoint\"
     :schema
     ((:path :type string :required t)
      (:method :type keyword :default :get))
     :behaviors (:add-skills :generate-handler)
     :commands t
     :storage :memory
     :searchable (:path :method :tags))"
  (let ((schema (getf body :schema))
        (behaviors (getf body :behaviors))
        (commands-p (getf body :commands))
        (storage (getf body :storage :memory))
        (searchable (getf body :searchable))
        (name-str (string-downcase (symbol-name name)))
        (def-macro-name (intern (format nil "DEF~A" (symbol-name name)) :hactar)))
    `(progn
       ;; Register entity type
       (setf (gethash ,name-str *entity-registry*)
             (make-entity-definition
              :name ',name
              :description ,description
              :schema ',schema
              :default-behaviors ',behaviors
              :commands-p ,commands-p
              :storage ,storage
              :searchable ',searchable))

       ;; Generate the def<entity> macro
       (defmacro ,def-macro-name (impl-name impl-description &body impl-body)
         ,(format nil "Define a ~A implementation.~%~
                       Generated by (defentity ~A ...)." name-str name-str)
         (let ((priority (getf impl-body :priority 0))
               (when-clause (getf impl-body :when))
               (options (getf impl-body :options))
               (skills (getf impl-body :skills))
               (schema-additions (getf impl-body :schema-additions))
               (create-fn (getf impl-body :create))
               (list-fn (getf impl-body :list))
               (update-fn (getf impl-body :update))
               (delete-fn (getf impl-body :delete)))
           `(register-entity-implementation
             ,',name-str
             (make-entity-implementation
              :name ',impl-name
              :entity-type ,',name-str
              :description ,impl-description
              :priority ,priority
              :when-fn ,(when when-clause `(lambda () ,when-clause))
              :options ',options
              :skills ',skills
              :schema-additions ',schema-additions
              :create-fn ,create-fn
              :list-fn ,list-fn
              :update-fn ,update-fn
              :delete-fn ,delete-fn))))

       ;; Generate CRUD commands if requested
       ,@(when commands-p
           (let ((create-cmd-name (format nil "~A.create" name-str))
                 (list-cmd-name (format nil "~A.list" name-str))
                 (find-cmd-name (format nil "~A.find" name-str))
                 (show-cmd-name (format nil "~A.show" name-str))
                 (update-cmd-name (format nil "~A.update" name-str))
                 (delete-cmd-name (format nil "~A.delete" name-str)))
             (declare (ignorable find-cmd-name show-cmd-name update-cmd-name))
             `(;; /entity.create command
               (setf (gethash ,create-cmd-name *commands*)
                     (list (lambda (args)
                             (if args
                                 (let ((entity-name (first args))
                                       (rest-args (rest args)))
                                   (apply #'entity/create ',name entity-name
                                          (parse-entity-command-args rest-args)))
                                 (format t "Usage: /~A.create <name> [options]~%" ,name-str)))
                           ,(format nil "Create a new ~A." name-str)))

               ;; /entity.list command
               (setf (gethash ,list-cmd-name *commands*)
                     (list (lambda (args)
                             (declare (ignore args))
                             (let ((results (entity/list ',name)))
                               (if results
                                   (dolist (r results)
                                     (if (entity-instance-p r)
                                         (format t "  ~A (id: ~A, tags: ~{~A~^, ~})~%"
                                                 (or (entity-get r :name) "unnamed")
                                                 (entity-instance-id r)
                                                 (entity-instance-tags r))
                                         (format t "  ~A~%" r)))
                                   (format t "No ~As found.~%" ,name-str))))
                           ,(format nil "List all ~As." name-str)))

               ;; /entity.find command
               (setf (gethash ,find-cmd-name *commands*)
                     (list (lambda (args)
                             (let ((tags-str (getf-string args "--tags")))
                               (let ((results (find-entity-instances ',name
                                                                     :tags (when tags-str (str:split "," tags-str)))))
                                 (if results
                                     (dolist (r results)
                                       (format t "  ~A (tags: ~{~A~^, ~})~%"
                                               (or (entity-get r :name) "unnamed")
                                               (entity-instance-tags r)))
                                     (format t "No ~As found.~%" ,name-str)))))
                           ,(format nil "Find ~As by criteria." name-str)))

               ;; /entity.show command
               (setf (gethash ,show-cmd-name *commands*)
                     (list (lambda (args)
                             (if args
                                 (let* ((target-name (first args))
                                        (instances (find-entity-instances ',name))
                                        (match (find target-name instances
                                                     :key (lambda (i) (entity-get i :name))
                                                     :test #'string-equal)))
                                   (if match
                                       (progn
                                         (format t "~A: ~A~%" ,name-str (entity-get match :name))
                                         (format t "  ID: ~A~%" (entity-instance-id match))
                                         (format t "  Tags: ~{~A~^, ~}~%" (entity-instance-tags match))
                                         (maphash (lambda (k v)
                                                    (format t "  ~A: ~A~%" k v))
                                                  (entity-instance-properties match)))
                                       (format t "~A not found: ~A~%" ,name-str target-name)))
                                 (format t "Usage: /~A.show <name>~%" ,name-str)))
                           ,(format nil "Show details of a ~A." name-str)))

               ;; /entity.update command
               (setf (gethash ,update-cmd-name *commands*)
                     (list (lambda (args)
                             (if args
                                 (let ((entity-name (first args))
                                       (rest-args (rest args)))
                                   (apply #'entity/update ',name entity-name
                                          (parse-entity-command-args rest-args)))
                                 (format t "Usage: /~A.update <name> [options]~%" ,name-str)))
                           ,(format nil "Update a ~A." name-str)))

               ;; /entity.delete command
               (setf (gethash ,delete-cmd-name *commands*)
                     (list (lambda (args)
                             (if args
                                 (entity/delete ',name (first args))
                                 (format t "Usage: /~A.delete <name>~%" ,name-str)))
                           ,(format nil "Delete a ~A." name-str)))

               ;; CLI subcommands
               (define-sub-command ,(intern (format nil "~A.create" name-str)) (args)
                 ,(format nil "Create a new ~A." name-str)
                 (if args
                     (let ((entity-name (first args))
                           (rest-args (rest args)))
                       (apply #'entity/create ',name entity-name
                              (parse-entity-command-args rest-args)))
                     (format t "Usage: hactar ~A.create <name> [options]~%" ,name-str)))

               (define-sub-command ,(intern (format nil "~A.list" name-str)) (args)
                 ,(format nil "List all ~As." name-str)
                 (declare (ignore args))
                 (let ((results (entity/list ',name)))
                   (if results
                       (dolist (r results)
                         (if (entity-instance-p r)
                             (format t "  ~A~%" (or (entity-get r :name) "unnamed"))
                             (format t "  ~A~%" r)))
                       (format t "No ~As found.~%" ,name-str)))))))

       ',name)))

;;** Command Argument Parser

(defun parse-entity-command-args (args)
  "Parse entity command arguments like --path /api --tags api,auth into a plist."
  (let ((plist '()))
    (loop for rest on args by #'cddr
          for arg = (first rest)
          for val = (second rest)
          when (and (stringp arg) (str:starts-with? "--" arg))
          do (let ((key (intern (string-upcase (subseq arg 2)) :keyword)))
               (cond
                 ;; Handle comma-separated lists for :tags
                 ((eq key :tags)
                  (setf (getf plist key) (str:split "," val)))
                 (t
                  (setf (getf plist key) val)))))
    plist))

;;** defentity-recipe

(defmacro defentity-recipe (name description &body body)
  "Define a multi-entity recipe.

   Usage:
   (defentity-recipe auth
     \"Add authentication\"
     :creates ((route :path \"/login\" ...) ...)
     :installs (\"jsonwebtoken\")
     :configures ((:env \"JWT_SECRET\" ...)))"
  (let ((creates (getf body :creates))
        (installs (getf body :installs))
        (configures (getf body :configures))
        (name-str (if (stringp name) name (string-downcase (symbol-name name)))))
    `(setf (gethash ,name-str *recipes*)
           (make-recipe
            :name ',name
            :description ,description
            :steps (append
                    ;; Install steps
                    (list ,@(mapcar (lambda (pkg) `(list :install ,pkg)) installs))
                    ;; Create steps from entity specs
                    (list ,@(mapcar (lambda (spec)
                                      (let ((entity-type (first spec))
                                            (entity-args (rest spec)))
                                        (declare (ignore entity-args))
                                        `(list :entity-create ',entity-type
                                               ,@(rest spec))))
                                    creates))
                    ;; Configure steps
                    (list ,@(mapcar (lambda (cfg)
                                      `(list :configure ',cfg))
                                    configures)))))))
