;; js-mode. wip. for now just analyzes package.json. Most cool features are in pro
(in-package :hactar)
(nhooks:define-hook-type package-json-analyzed (function (hash-table) t)
  "Hook run after a package.json file is analyzed. Handler takes a hash-table of metadata.")
(defvar *package-json-analyzed-hook* (make-instance 'hook-package-json-analyzed))
(defun is-package-json-event? (pathname event-type)
  (debug-log
    (format nil "~&Checking package.json event: ~A~%" pathname)
    (format nil "~&Event type: ~A~%" event-type))
  (and (or (eq event-type :file-added) (eq event-type :file-changed))
       (string= (pathname-name pathname) "package")
       (string= (pathname-type pathname) "json")))

(def-analyzer package-json ((*file-event-hook* #'is-package-json-event?)) nil (pathname event-type)
              "Analyzes a package.json file and runs the package-json-analyzed hook."
              (declare (ignore event-type))
              (debug-log "Running package-json analyzer for:" pathname)
              (handler-case
                  (let* ((content (uiop:read-file-string pathname))
                         (json (cl-json:decode-json-from-string content))
                         (metadata (make-hash-table :test 'equal)))
                    (debug-log
                      (format nil "~&Analyzing package.json: ~A~%" pathname))
                    (setf (gethash "scripts" metadata) (cdr (assoc :scripts json)))
                    (setf (gethash "project-name" metadata) (cdr (assoc :name json)))
                    (setf (gethash "language" metadata) "javascript")
                    (setf *language* "javascript")
                    (setf (gethash "dependencies" metadata) (cdr (assoc :dependencies json)))
                    (setf (gethash "dev-dependencies" metadata) (or (cdr (assoc :dev-dependencies json))
                                                                    (cdr (assoc :dev--dependencies json))))
                    (let ((deps (mapcar #'car (gethash "dependencies" metadata)))
                          (dev-deps (mapcar #'car (gethash "dev-dependencies" metadata))))
                      (when (or (member "typescript" deps :test #'string=) (member "typescript" dev-deps :test #'string=))
                        (setf (gethash "language" metadata) "typescript")
                        (setf *language* "typescript")))
                    (setf (gethash "stack" metadata) *stack*)
                    (nhooks:run-hook *package-json-analyzed-hook* metadata))
                (error (e)
                  (format t "~&Error analyzing ~A: ~A~%" pathname e))))
