# Created 2025-12-06 Sat 17:01
#+title: Hactar
#+author: k
* README
Hactar is an augmented coding assistant that lives in your editor or terminal of choice. No AI hype bullshit, no agents, no vibe coding, just a tool that helps you write, debug, and iterate on code faster. An AI coding tool for devs doing serious work in tools they’ve spent decades mastering.

Hactar's core feature is tight integration with a knowledge repository. It leverages well written, meticulously crafted developer documentation that dramatically increases the quality of code generated by SOTA models. You can think of it like devdocs + starter kits + AI assistant. The starter kit era brought into the agent era.

Hactar places an emphasis on hackability and integration. Hactar isn't a closed-source black box or a CLI designed to be used with proprietary protocols. It is a first-class citizen in your developer experience. You can modify it on the fly while you work (and it will help with those modifications). Hactar uses both LLMs and hardcode knowledge to accomplish tasks. We don't wrap things up in a Vscode fork we tightly integrate with Emacs, Neovim, and the CLI. If you are a LISPer, Rubyist etc, you will feel right at home.

Some of Hactar's features:

- *Smart Context*
  Hactar is the only AI tool integrated with a content repository (paid or bring your own). Millions of notes, error messages and solutions, examples, snippets, etc., pulled directly from realworld projects give Hactar unparalleled skills.
- *Hackable and Extensible*
  Hactar is explicitly designed to be extended while you work. When you discover gaps in the LLM's knowledge, you can patch it for later.
- *Bring Your Own Key*
  No pricing changes or being tied to any specific model. Hactar supports all major providers, from Ollama to OpenRouter.
- *Tight Ecosystem Integration*
  Hactar is for developers who live and breathe their editors. Neovim and Emacs are integrated using community standards. No Vscode forks here.
- *Agents that Never Break*
  Hactar agents don't do vibe coding. They are specifically designed to only code what works 99% of the time. Hactar agents manage configs, update dependencies, run tests, etc. These small wins add up when they work flawlessly.
- *Unix Philosophy*
  Hactar exposes the context as a file that it fully understands. You can add and drop files by writing plain text and linking to them. This makes it trivial to use everything from Emacs tooling to grep and sed to manage your context.
- *Old School Hard Coded Intelligence*
  Hactar uses "modes" to provide intelligent contextual knowledge to an LLM. With the magic of hard coding we can do things like look up docs for a React API in ms instead of seconds.
** Quickstart
The quickest way:

#+begin_src sh
  curl -L https://hactar.space/install.sh | bash
#+end_src

Nix:

#+begin_src sh
  nix profile install "github:hactar-project/hactar"
  hactar hactar.init
#+end_src

GitHub Releases:

#+begin_src sh
  cd ~/.local/bin && wget -qO- https://github.com/hactar-project/hactar/releases/latest/download/hactar-0.1.tar.gz | tar -xz -C hactar
  hactar hactar.init
#+end_src

*Important*: You'll need to run =hactar hactar.init= if you install using anything other than the script.

Now you can run hactar in any git repo:

#+begin_src sh
  hactar
#+end_src

You'll want to set API keys. Any of the following will do:

- =OPENAI_API_KEY=: The API key for OpenAI models
- =ANTHROPIC_API_KEY=: The API key for Anthropic models
- =GEMINI_API_KEY=: he API for vertex/google ai studio
- =OPENROUTER_API_KEY=: The OpenRouter api key.

You'll likely want to set a model you can do this with an environment variable =HACTAR_MODEL=. In this case a github_copilot model:

#+begin_src sh
  env HACTAR_MODEL="github_copilot/gemini-2.5-pro" hactar
#+end_src

Now you will want to setup your editor:

Emacs:

#+begin_src emacs-lisp
  (use-package hactar
       :straight (:host "github" :repo "hactar-project/hactar.el" :files ("*.el"))
      :config
  (setq hactar-args '("--model" "gemini/gemini-2.5-pro-preview-06-05"))
  :bind
  ("C-c h" . hactar-transient-menu)
  ("C-x g h s" . hactar-sonnet)
  ("C-x g h d" . hactar-deepseek)
  ("C-x g h g" . hactar-gemini)
  ("C-x g h t" . hactar-gemini-thinking)
  ("C-x g h o" . hactar-o3-mini))
#+end_src

Neovim:

#+begin_src lua
  {
     'hactar-project/hactar.nvim',
  ---@module 'oil'
  ---@type oil.SetupOpts
  opts = {},
  -- Optional dependencies
  dependencies = { { "echasnovski/mini.icons", opts = {} } },
  -- dependencies = { "nvim-tree/nvim-web-devicons" }, -- use if you prefer nvim-web-devicons
  -- Lazy loading is not recommended because it is very tricky to make it work correctly in all situations.
  lazy = false,
  }
#+end_src
** Learn More
- [[https://docs.hactar.space][The Docs]]
- [[https://github.com/hactar-project/hactar.el][hactar.el]] The emacs extension
- [[https://github.com/hactar-project/hactar.nvim][hactar.nvim]] The neovim extension
- [[https://roadmap.hactar.space][Roadmap]]
- [[https://changelog.hactar.space][Changelog]]
- [[https://devlog.mostlyuseless.space][Dev Log]] The daily developer log of k-2052
- [[https://hactar.space][Hactar Pro]] (gives you access to a content repo)
- [[https://buildformachines.mostlyuseless.space][Building for Machines]] A book on context engineer, LLM integrations and buildng dev tools for LLMs
