(in-package :hactar-tests)

(def-suite agent-testagent-tests
  :description "Tests for TEST agent lifecycle and retry behavior.")

(in-suite agent-testagent-tests)

(test test-agent-def-exists "test agent definition exists"
  (let ((agent-def (gethash (intern "TEST" :hactar) hactar::*agent-definitions*)))
    (is-true agent-def)))

(test test-succeeds-first-try "Test agent succeeds on first try"
  (let ((hactar::*live-dangerously* t)
        (hactar::*test-agent-command* "echo 'test success'")
        (agent-def (gethash (intern "TEST" :hactar) hactar::*agent-definitions*)))
    (with-dynamic-stubs ((uiop:run-program (lambda (cmd &key &allow-other-keys)
                                             (declare (ignore cmd))
                                             (values "output" "" 0)))
                         (hactar::get-llm-response (lambda (prompt &key &allow-other-keys)
                                                     (declare (ignore prompt))
                                                     (fail "get-llm-response should not be called")
                                                     "")))
      (let ((instance (hactar::start-agent agent-def nil)))
        (is-true instance)
        (bt:join-thread (hactar::agent-instance-thread instance))
        (is (= 1 (hactar::agent-instance-retry-count instance)))
        (is (= 0 (hactar::agent-instance-last-command-status instance)))))))

(test test-fails-once-then-succeeds "Test agent fails once, then succeeds"
  (let ((hactar::*live-dangerously* t)
        (hactar::*test-agent-command* "fail-then-succeed")
        (agent-def (gethash (intern "TEST" :hactar) hactar::*agent-definitions*))
        (run-program-call-count 0)
        (get-llm-response-call-count 0))
    (with-dynamic-stubs ((uiop:run-program (lambda (cmd &key &allow-other-keys)
                                             (declare (ignore cmd))
                                             (incf run-program-call-count)
                                             (if (= run-program-call-count 1)
                                                 (values "" "error" 1)
                                                 (values "" "" 0))))
                         (hactar::get-llm-response (lambda (prompt &key &allow-other-keys)
                                                     (declare (ignore prompt))
                                                     (incf get-llm-response-call-count)
                                                     "some SEARCH/REPLACE block")))
      (let ((instance (hactar::start-agent agent-def nil)))
        (is-true instance)
        (bt:join-thread (hactar::agent-instance-thread instance))
        (is (= 2 (hactar::agent-instance-retry-count instance)))
        (is (= 0 (hactar::agent-instance-last-command-status instance)))
        (is (= 1 get-llm-response-call-count))))))

(test test-reaches-retry-limit "Test agent fails until retry limit"
  (let ((hactar::*live-dangerously* t)
        (hactar::*agent-retry-limit* 3) ; Set a specific limit for this test
        (hactar::*test-agent-command* "always-fail")
        (agent-def (gethash (intern "TEST" :hactar) hactar::*agent-definitions*))
        (get-llm-response-call-count 0))
    (with-dynamic-stubs ((uiop:run-program (lambda (cmd &key &allow-other-keys)
                                             (declare (ignore cmd))
                                             (values "" "error" 1)))
                         (hactar::get-llm-response (lambda (prompt &key &allow-other-keys)
                                                     (declare (ignore prompt))
                                                     (incf get-llm-response-call-count)
                                                     "some SEARCH/REPLACE block")))
      (let ((instance (hactar::start-agent agent-def nil)))
        (is-true instance)
        (bt:join-thread (hactar::agent-instance-thread instance))
        (is (= 3 (hactar::agent-instance-retry-count instance)))
        (is (= 1 (hactar::agent-instance-last-command-status instance)))
        (is (= 3 get-llm-response-call-count))))))
